#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_numero_sorteo:
    path: /sorteo/numero/{maximo}
    controller: App\Controller\SorteoController::numero
    defaults:
        maximo: 100

app_suma:
    path: /suma/{minimo}/{maximo}
    controller: App\Controller\Suma::numero
    defaults:
        minimo: 2
        maximo: 2

app_ejercicio53:
    path: /
    controller: App\Controller\SorteoController::index

app_ejercicio54:
    path: /sorteo/euromillones
    controller: App\Controller\SorteoController::euromillones

app_ejercicio55:
    path: /seccionActual
    controller: App\Controller\SorteoController::seccionActual

app_nueva_apuesta:
    path: /sorteo/apuestas/nueva
    controller: App\Controller\SorteoController::nuevaApuesta
    
app_apuesta_creada:
    path: /apuesta/creada
    controller: App\Controller\SorteoController::apuestaCreada